<?php

/**
 * @file
 * Provides an elections candidate entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function localgov_elections_theme() {
  return [
    'localgov_elections_candidate' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for elections candidate templates.
 *
 * Default template: localgov-elections-candidate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the elections candidate information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_localgov_elections_candidate(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
